# https://argo-cd.readthedocs.io/en/stable/user-guide/helm/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: redis
spec:
  destination:
    namespace: redis
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: bitnami/redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 7.4.0
